name: Java CI & Quality Gate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Validar nombre de la rama (Ej: feature/..., bugfix/..., hotfix/...)
      - name: Validate Branch Name
        run: |
          # github.head_ref es el nombre de la rama en un Pull Request
          BRANCH_NAME="${{ github.head_ref }}"

          # Explicación del REGEX:
          # ^[0-9]{4}  -> Debe empezar con exactamente 4 números del 0 al 9
          # \-         -> Seguido de un guion literal
          # .+         -> Seguido de cualquier carácter (al menos uno)
          # $          -> Fin de la cadena
          REGEX="^[0-9]{4}\-.+$"

          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "-------------------------------------------------------"
            echo "ERROR: NOMBRE DE RAMA INVÁLIDO"
            echo "Tu rama se llama: $BRANCH_NAME"
            echo "El formato debe ser: 0000-nombre-de-la-tarea"
            echo "Ejemplo: 1234-login-fix"
            echo "-------------------------------------------------------"
            exit 1
          fi
      # 2. Configurar Entorno
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Validar Formato de Commits (Conventional Commits)
      # Esto revisa que los commits del PR empiecen por feat:, fix:, docs:, etc.
      - name: Validate Commit Messages
        uses: wagoid/commitlint-github-action@v5

      # 4. Ejecutar Build (Sin tests primero para asegurar compilación)
      - name: Build Project
        run: mvn clean compile

      # 5. Ejecutar Tests Automáticos
      - name: Run Tests
        run: mvn test

      # 1. Construir la imagen de Docker
      - name: Build Docker Image
        run: docker build -t mi-proyecto-app:latest .

      # 2. Listar imágenes y filtrar por el tamaño de la nuestra
      - name: Show Docker Image Size
        run: |
          IMAGE_SIZE=$(docker images --format "{{.Size}}" mi-proyecto-app:latest)
          echo "### 🚀 Reporte de Docker" >> $GITHUB_STEP_SUMMARY
          echo "La imagen se ha generado correctamente." >> $GITHUB_STEP_SUMMARY
          echo "- **Nombre:** mi-proyecto-app:latest" >> $GITHUB_STEP_SUMMARY
          echo "- **Tamaño:** $IMAGE_SIZE" >> $GITHUB_STEP_SUMMARY
          echo "El tamaño detectado es: $IMAGE_SIZE"